#!/usr/bin/env python
"""Generate Table 2 (the Data-section multi-panel super table) from the frozen snapshot.

Panel A  records by year and KABCO outcome
Panel B  covariate profile across the severity ladder (with inline data bars)
Panel C  feature blocks and completeness

Reads only the authorized analysis snapshot. Emits LaTeX to stdout and to
reproducibility/tables/table2_data.tex. Never hand-type a number into the .tex.

Run:  python reproducibility/tables/make_table2.py
"""
import json
import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = next((p for p in Path(__file__).resolve().parents
             if (p / "experiments" / "results").is_dir()), None)
if ROOT is None:
    raise FileNotFoundError("Could not locate experiments/results from the table exporter")
SNAP = Path(os.environ.get(
    "CHOIR_ANALYSIS_PARQUET",
    ROOT / "data" / "processed" / "analysis.parquet",
))
OUT = Path(__file__).resolve().parent / "table2_data.tex"

KABCO = {1: "O", 2: "C", 3: "B", 4: "A", 5: "K"}
CONT = ["speed_limit", "adt", "hour", "age", "vehicle_age", "doors",
        "displacement_l", "engine_hp"]
CAT = ["Wthr_Cond_ID", "Light_Cond_ID", "Surf_Cond_ID", "Road_Type_ID", "Road_Algn_ID",
       "Traffic_Cntl_ID", "Intrsct_Relat_ID", "Rural_Fl", "Func_Sys_ID", "Road_Cls_ID",
       "Day_of_Week", "Prsn_Gndr_ID", "Prsn_Rest_ID", "Drvr_Lic_Type_ID",
       "Drvr_Lic_Cls_ID", "Prsn_Type_ID", "BodyClass", "VehicleType", "GVWR",
       "DriveType", "ESC", "CIB", "ForwardCollisionWarning", "LaneDepartureWarning",
       "BlindSpotMon", "AirBagLocCurtain", "AirBagLocSide", "Pop_Group_ID"]
BOOL = ["vin_undecoded", "has_geo"]

# Feature-block assignment for Panel C (Config P semantics, Section 3).
BLOCK = {
    "crash context": ["speed_limit", "adt", "hour", "Wthr_Cond_ID", "Light_Cond_ID",
                      "Surf_Cond_ID", "Road_Type_ID", "Road_Algn_ID", "Traffic_Cntl_ID",
                      "Intrsct_Relat_ID", "Func_Sys_ID", "Road_Cls_ID", "Day_of_Week"],
    "person": ["age", "Prsn_Gndr_ID", "Prsn_Rest_ID", "Drvr_Lic_Type_ID",
               "Drvr_Lic_Cls_ID", "Prsn_Type_ID"],
    "vehicle (VIN)": ["vehicle_age", "doors", "displacement_l", "engine_hp",
                      "BodyClass", "VehicleType", "GVWR", "DriveType", "ESC", "CIB",
                      "ForwardCollisionWarning", "LaneDepartureWarning", "BlindSpotMon",
                      "AirBagLocCurtain", "AirBagLocSide", "vin_undecoded"],
    "geography": ["Rural_Fl", "Pop_Group_ID", "has_geo"],
}


def databar(frac, width=1.05, color="seqteal3"):
    """Inline proportional bar behind a Panel-B share."""
    frac = 0.0 if not np.isfinite(frac) else max(0.0, min(1.0, float(frac)))
    return (f"\\databar{{{frac:.4f}}}")


def main():
    if not SNAP.exists():
        sys.exit(f"snapshot not found: {SNAP}")
    # The snapshot holds ALL 9,078,415 valid-severity driver rows. The paper's
    # population is the 5,213,921 PRIMARY one-driver-per-crash rows (Remark 0.1),
    # selected by the `primary_row` flag exactly as experiments/common.py
    # load_primary() does. Filtering here is mandatory: without it every number in
    # this table describes a different population than the results section.
    cols = list(dict.fromkeys(
        ["crash_year", "y_kabco", "Rural_Fl", "VehicleType", "Veh_Body_Styl_ID",
         "Prsn_Gndr_ID", "primary_row"] + CONT + CAT + BOOL))
    df = pd.read_parquet(SNAP, columns=[c for c in cols if c])
    n_all = len(df)
    df = df[df["primary_row"].astype(bool)].drop(columns=["primary_row"])
    n = len(df)
    meta = json.loads((SNAP.parent / "analysis_meta.json").read_text())
    expect = meta["waterfall"]["6_primary_rows_one_per_crash"]
    if n != expect:
        sys.exit(f"primary-row count {n:,} != snapshot meta {expect:,}")
    for k, v in meta["kabco_primary"].items():
        got = int((df.y_kabco == int(k)).sum())
        if got != v:
            sys.exit(f"KABCO {k}: got {got:,} != meta {v:,}")
    sys.stderr.write(f"[check] {n_all:,} valid-severity rows -> {n:,} primary rows; "
                     f"KABCO totals match analysis_meta.json\n")
    L = []
    L.append("% GENERATED by reproducibility/tables/make_table2.py — do not hand-edit.")
    L.append(f"% snapshot rows: {n}")

    # ---------------- Panel A: year x outcome ----------------
    A = pd.crosstab(df["crash_year"], df["y_kabco"])
    A = A.reindex(columns=[1, 2, 3, 4, 5], fill_value=0)
    A["Total"] = A.sum(axis=1)
    tot = A.sum(axis=0)

    # ---------------- Panel B: covariate profile across the ladder ----------------
    # SENTINEL HANDLING (disclosed in the table notes; see DECISIONS.md 2026-07-16).
    # `speed_limit` carries a -1 sentinel on 244,965 primary rows (4.70%) and
    # `vehicle_age` is negative on 18,335 rows (model year ahead of crash year).
    # Neither is NaN, so both enter the design matrix as literal numbers and both are
    # reported as "0.00% / 0.48% missing" by a naive isna() count. Descriptive
    # statistics here are computed on VALID values only and the exclusions are stated
    # in the notes; the models are fit on the columns as they stand.
    sl = pd.to_numeric(df["speed_limit"], errors="coerce")
    va = pd.to_numeric(df["vehicle_age"], errors="coerce")
    sl_valid, va_valid = sl > 0, va >= 0
    # Count the SENTINELS ONLY. `~(va >= 0)` is True for NaN as well as for negatives,
    # so it silently folds the 25,148 MISSING vehicle ages into a count the note labels
    # "model year later than the crash year", giving 43,483 where the truth is 18,335
    # (found by Referee A: the note contradicted the prose). Missingness is Panel C's
    # business; this note is about sentinels.
    n_sl_sent = int((sl <= 0).sum())
    n_va_neg = int((va < 0).sum())

    rows_b = {}
    g = df.groupby("y_kabco")
    rows_b["$n$"] = {k: int((df.y_kabco == k).sum()) for k in range(1, 6)}
    rows_b["mean speed limit (mph)"] = {
        k: float(sl[sl_valid & (df.y_kabco == k)].mean()) for k in range(1, 6)}
    rows_b["rural share"] = g["Rural_Fl"].apply(
        lambda s: (s.astype(str).str.upper().isin(["Y", "TRUE", "1"])).mean()).to_dict()
    # Motorcycle share uses CRIS's OWN reported body style, not the VIN decode: it is
    # populated for every row, whereas VehicleType is missing wherever the VIN failed
    # to decode (~3%). This is the definition behind the FIGURES_PLAN anchors.
    mc = df["Veh_Body_Styl_ID"].astype(str).str.contains("Motorcycle", case=False, na=False)
    rows_b["motorcycle-driver share"] = df.assign(_mc=mc).groupby("y_kabco")["_mc"].mean().to_dict()
    rows_b["median ADT (known)"] = g["adt"].median().to_dict()
    rows_b["mean driver age"] = g["age"].mean().to_dict()
    fem = df["Prsn_Gndr_ID"].astype(str).str.upper().str.startswith("F")
    rows_b["female share"] = df.assign(_f=fem).groupby("y_kabco")["_f"].mean().to_dict()
    rows_b["median vehicle age (yr)"] = {
        k: float(va[va_valid & (df.y_kabco == k)].median()) for k in range(1, 6)}
    rows_b["VIN undecoded"] = g["vin_undecoded"].mean().to_dict()
    rows_b["geocoded"] = g["has_geo"].mean().to_dict()

    # ---------------- Panel C: completeness ----------------
    miss = {c: float(df[c].isna().mean()) for c in CONT}
    levels = {c: int(df[c].nunique(dropna=True)) for c in CAT}

    # ================= emit =================
    L.append(r"\begin{table}[pos=htbp]")
    L.append(r"\caption{Composition of the analysis sample.}\label{tbl:data}")
    L.append(r"\centering\footnotesize")
    L.append(r"\begin{threeparttable}")
    L.append(r"\begin{tabular*}{\tblwidth}{@{\extracolsep{\fill}}l" + "r" * 6 + "@{}}")
    L.append(r"\toprule")
    L.append(r"\multicolumn{7}{@{}l}{\textsc{Panel A. Driver records by year and reported outcome}}\\")
    L.append(r"\midrule")
    L.append(r"Year & \cellcolor{seqteal1}O & \cellcolor{seqteal1}C & "
             r"\cellcolor{seqteal2}B & \cellcolor{seqteal3}A & "
             r"\cellcolor{seqteal4}\textcolor{white}{K} & Total\\")
    L.append(r"\midrule")
    for y, r in A.iterrows():
        cells = " & ".join(f"{int(r[k]):,}" for k in [1, 2, 3, 4, 5])
        note = r"\tnote{a}" if int(y) == 2020 else ""
        L.append(f"{int(y)}{note} & {cells} & {int(r['Total']):,}\\\\")
    L.append(r"\cmidrule{1-7}")
    cells = " & ".join(f"\\textbf{{{int(tot[k]):,}}}" for k in [1, 2, 3, 4, 5])
    L.append(f"\\textbf{{Total}} & {cells} & \\textbf{{{int(tot['Total']):,}}}\\\\")

    L.append(r"\midrule")
    L.append(r"\multicolumn{7}{@{}l}{\textsc{Panel B. Covariate profile across the severity ladder}}\\")
    L.append(r"\midrule")
    L.append(r" & \cellcolor{seqteal1}O & \cellcolor{seqteal1}C & \cellcolor{seqteal2}B "
             r"& \cellcolor{seqteal3}A & \cellcolor{seqteal4}\textcolor{white}{K} & \\")
    L.append(r"\midrule")
    share_rows = {"rural share", "motorcycle-driver share", "female share",
                  "VIN undecoded", "geocoded"}
    for label, d in rows_b.items():
        vals = []
        for k in range(1, 6):
            v = d.get(k, np.nan)
            if label == "$n$":
                vals.append(f"{int(v):,}")
            elif label in share_rows:
                vals.append(f"{databar(v)}{v:.3f}".replace("0.", "."))
            elif "median ADT" in label:
                vals.append("--" if not np.isfinite(v) else f"{int(round(v)):,}")
            elif "vehicle age" in label or label == "median vehicle age (yr)":
                vals.append(f"{v:.0f}")
            else:
                vals.append(f"{v:.1f}")
        note = ""
        if "ADT" in label:
            note = r"\tnote{b}"
        L.append(f"{label}{note} & " + " & ".join(vals) + r" & \\")

    # ---- Panel C. Rows are the four Config-P feature blocks; the eight continuous
    # features and their missingness are spelled out per block in the last column,
    # which is where the actionable information is.
    # NOTE: `\tblwidth` is a MACRO that expands to a printed dimension string (via
    # \dim_use:N), not a length register. It therefore cannot be scaled: both
    # `p{0.4\tblwidth}` and `p{\dimexpr 0.4\tblwidth\relax}` raise "Illegal unit of
    # measure". Use \textwidth for any p-column. Do not "fix" this back.
    L.append(r"\midrule")
    L.append(r"\multicolumn{7}{@{}l}{\textsc{Panel C. Feature blocks and completeness "
             r"(Configuration P)}}\\")
    L.append(r"\midrule")
    L.append(r"Block & cont. & categ. & ind. & levels & \multicolumn{2}{c}{"
             r"continuous features (\% missing)}\\")
    L.append(r"\midrule")
    for blk, feats in BLOCK.items():
        c_cont = [f for f in feats if f in CONT]
        c_cat = [f for f in feats if f in CAT]
        c_bool = [f for f in feats if f in BOOL]
        nlev = sum(levels[f] for f in c_cat)
        pretty = {"speed_limit": "speed limit", "adt": "ADT", "hour": "hour",
                  "age": "driver age", "vehicle_age": "vehicle age", "doors": "doors",
                  "displacement_l": "displacement", "engine_hp": "engine power"}
        cont_s = ", ".join(
            f"{pretty.get(f, f)}~{miss[f]*100:.2f}" for f in c_cont) or "--"
        L.append(f"{blk} & {len(c_cont)} & {len(c_cat)} & {len(c_bool)} & "
                 f"{nlev if c_cat else '--'} & "
                 f"\\multicolumn{{2}}{{p{{0.40\\textwidth}}}}"
                 f"{{\\raggedright\\scriptsize {cont_s}}}\\\\")
    L.append(r"\cmidrule{1-7}")
    L.append(f"\\textbf{{Total}} & \\textbf{{{len(CONT)}}} & \\textbf{{{len(CAT)}}} & "
             f"\\textbf{{{len(BOOL)}}} & \\textbf{{{sum(levels.values())}}} & "
             r"\multicolumn{2}{p{0.40\textwidth}}{\raggedright\scriptsize "
             r"one-hot encoded at a 0.005 minimum frequency; rarer levels pooled}\\")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular*}")
    L.append(r"\begin{tablenotes}\footnotesize")
    L.append(r"\item[a] The 2020 total is the lowest in the series.")
    L.append(r"\item[b] ADT is " + f"{miss['adt']*100:.2f}" +
             r"\% missing and engine power " + f"{miss['engine_hp']*100:.2f}" +
             r"\% missing; both enter the design matrix with median imputation and a "
             r"missingness indicator, so no record is dropped for incompleteness.")
    L.append(r"\item[c] Panel B statistics for posted speed limit exclude the "
             + f"{n_sl_sent:,}" + r" records (" + f"{n_sl_sent/n*100:.2f}"
             + r"\%) carrying the CRIS $-1$ sentinel, and those for vehicle age exclude "
             + f"{n_va_neg:,}" + r" records with a model year later than the crash year. "
             r"Both values are sentinels rather than nulls, so Panel C's missingness "
             r"counts do not register them; the fitted models see the columns as stored. "
             r"Motorcycle share is the CRIS-reported body style, which is populated for "
             r"every record, rather than the VIN decode.")
    L.append(r"\end{tablenotes}")
    L.append(r"\end{threeparttable}")
    L.append(r"\end{table}")

    OUT.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))

    # -------- anchors echoed for the numbers audit --------
    sys.stderr.write("\n===== ANCHORS FOR AUDIT =====\n")
    sys.stderr.write(f"total rows        : {n:,}\n")
    sys.stderr.write(f"KABCO totals      : " + ", ".join(
        f"{KABCO[k]}={int(tot[k]):,}" for k in range(1, 6)) + "\n")
    sys.stderr.write(f"year totals       : " + ", ".join(
        f"{int(y)}={int(r['Total']):,}" for y, r in A.iterrows()) + "\n")
    sys.stderr.write("panel B:\n")
    for label, d in rows_b.items():
        sys.stderr.write(f"  {label:28s} " + " ".join(
            f"{d.get(k, float('nan')):.4f}" if label != "$n$" else f"{int(d.get(k,0)):,}"
            for k in range(1, 6)) + "\n")
    sys.stderr.write("continuous missingness: " + ", ".join(
        f"{c} {miss[c]*100:.2f}%" for c in CONT) + "\n")
    sys.stderr.write(f"categorical count: {len(CAT)}, continuous: {len(CONT)}, bool: {len(BOOL)}\n")


if __name__ == "__main__":
    main()
